### ISSUE TITLE
profile picture is not updating 

### ISSUE THREAD

**Issue by jocatalin** [PoBuchi/meteor-accounts-linkedin#10]
If you change your profile picture in LinkedIn, the pictureUrl field from the Users collection is not being updated. I get this error in the browser console when I try to display the pictureUrl field:
Failed to load resource: the server responded with a status of 404 (Not Found)
How to replicate: 
Change your picture in LinkedIn and try to browse to the URL from pictureUrl field (https://media.licdn.com/xxx...)

**Comment by PauliBuccini** [comment]
Because LinkedIn changes your pictures url. and we don't have reactive connection with LinkedIn to know about changes

**Comment by andr33a** [comment]
But if you log out and log in again, shouldn't your data be refreshed?

**Comment by PauliBuccini** [comment]
Well I haven't see this type of behavior on other login packages, but maybe we can do it
