### ISSUE TITLE
Existing users get new accounts when logging in

### ISSUE THREAD

**Issue by brettle** [PoBuchi/meteor-accounts-linkedin#14]
This issue was [reported on stackoverflow](http://stackoverflow.com/questions/33014903/meteor-signin-with-linkedin-not-recognizing-existing-users). The problem is that `pauli:linkedin` retrieved user IDs from the wrong place and LinkedIn recently changed the values stored in that place. As a result, existing users have a value in `services.linkedin.id` that doesn't correspond to anything that LinkedIn returns as part of an OAuth response. As a result, the IDs of all existing users need to migrated, if possible.

Proposed fix:
1. Add a `services.linkedin.idIsFixed` property and index it for efficiency.
2. On the server at startup, for each account which has a value for `services.linkedin.id` but doesn't have a value of `true` for `services.linkedin.idIsFixed`:
   1. Use `services.linkedin.accessToken` to request the user's correct id from LinkedIn.
   2. Update `services.linkedin.id` with the obtained value, and set `services.linkedin.idIsFixed` to `true`.

There are 2 wrinkles in this plan:
1. Some users will have multiple accounts because they attempted to log in before the fix was deployed. The old account will probably have more app information associated with it, but the new account will have more recent app info associated with it. Which account should the user be logged into in the future and what should happen to the other account? Maybe we should allow the app to register a callback that is called when this situation is encountered?
2. Some access tokens may have expired. I **think** the access tokens expire after about 60 days. So, if a user last signed in with LinkedIn more than about 60 days before the migration occurs, his ID would not be fixed by the migration. Depending on the app's configuration, such a user might be able to continue to access his account using other login services (e.g. using his Meteor "resume" login tokens from a computer where he previously logged in). We could conceivably detect when such a user logs in, and require that they sign in to LinkedIn again and replace his `services.linkedin` info. My `brettle:accounts-add-service` package might be useful for such a case. Regardless, this wouldn't handle users who don't have any other way of accessing their account. When such a user logs in with LinkedIn, we could see whether his `publicProfileUrl` matches that of an existing account, and if it does, update the ID on that account and log the user into it. Of course, this will only work if LinkedIn hasn't and doesn't change the format of that URL.

Thoughts?

**Comment by brettle** [comment]
It appears that [the `publicProfileUrl` can be customized by the user](https://help.linkedin.com/app/answers/detail/a_id/87) but the customized URL appears to always start with `https://www.linkedin.com/in/`, whereas the unedited form seems to start with `https://www.linkedin.com/pub/`. It would presumably be secure to use the unedited form to identify users, but in rare cases it wouldn't be secure to use the customized form. Specifically, if a user customized his profile URL, then used LinkedIn to log into the app, then customized his profile URL again but didn't log into the app using LinkedIn afterward, then LinkedIn allowed an attacker  to use the original customized URL. Under those circumstances, the attacker could gain access to the app as the user.

**Comment by samudranb** [comment]
Was this fixed? @brettle

**Comment by brettle** [comment]
Not that I'm aware of.

**Comment by svda** [comment]
This has been fixed yes.
