### ISSUE TITLE
invalid redirect_uri. This value must match a URL registered with the API Key.

### ISSUE THREAD

**Issue by agrawal-mohit** [PoBuchi/meteor-accounts-linkedin#16]
I'm getting an error for these uris :
- http://localhost:3000
- http://localhost:3000/auth/linkedin/callback 

Do I need to configure something ?

**Comment by PauliBuccini** [comment]
Please full example

**Comment by agrawal-mohit** [comment]
I've registered an application on LinkedIn with the above mentioned redirect_uri s. 

Added the package using - meteor add pauli:accounts-linkedin

Restarted the application - registered my client id and key.

Clicked the 'Signin with Linkedin' button and was redirected to linkedin page which shows the above error. 

Please point out specifically any more information you need.

**Comment by piyushmahensaria** [comment]
I got the same issue too, https://naveengopisetty.wordpress.com/2014/09/15/linkedin-oauth-2-0-issue-invalid-redirect_uri-this-value-must-match-a-url-registered-with-the-api-key/ was helpful.
Basically, on the error page, see the url, and look for redirect_uri, and copy paste it in your linkedin dev account oauth2 redirect field. (P.S. copy only redirect_uri, and not scope, which it follows.)

**Comment by jeremyevans6** [comment]
My issue was resolved with piyushmahensaria's advice. Thank you!

I suspect it is the same for everyone using this package, so I will post it here with brackets to indicate places that are variable in your implementation:

http[s]://[yourDomain.tld]**/_oauth/linkedin**

**Comment by jeremyevans6** [comment]
This worked briefly but now, strangely, it is failing again with the same error and the redirect URI listed lacks a tld.... This is a dead-end, unfortunately, because, while I can add a non-.com version of the authorized callback, it simply cannot visit that page which is not indexed through a tld. Advice?

**Comment by SakisKarakasiliotis** [comment]
@piyushmahensaria This worked properly for my case too. Thank you kind sir!
