### ISSUE TITLE
Name or email not showing, in UI.

### ISSUE THREAD

**Issue by piyushmahensaria** [PoBuchi/meteor-accounts-linkedin#17]
I have used meteor official accounts-ui, accounts-password, accounts-facebook and this linkedin package, but only in case of linkedin, after logging in, in the login hyperlink, name/email does not show up, only a down arrow. (as can be seen in top left corner of screenshot.), where as in case of facebook, name shows, and in case of accounts-password, email shows up.
![screenshot from 2015-12-15 12 58 12](https://cloud.githubusercontent.com/assets/12864068/11804675/93f5c8ca-a32b-11e5-919b-e4ab1869f25c.png)

**Comment by Merkurijus** [comment]
Could you collaborate how you setup your permissions?
Do you request for 'r_basicprofile' permissions on login?

#15 might help you.

**Comment by nolandg** [comment]
I have similar issue. I am requesting r_basicprofile and the information is received by Meteor. When I check Meteor.user(), the name and email properties are filled. But nothing appears in the UI, it seems the accounts-ui is not getting the name or email from linkedin. It works well using Google.

Any thoughts?

**Comment by nvtdev** [comment]
I had the same problem, the thing is in the user object there are _firstName _and _lastName _fields but NOT a _name_ field and this is the one used with the login buttons. I tried assigning that field upon registration but I'm still a newbie at Meteor  so couldn't do it and switched to this package:

https://atmospherejs.com/jonperl/accounts-linkedin

If someone figures a way to do it though please share how.

**Comment by raza2022** [comment]
@nvtdev same issue am just tried a hack! but works :
Meteor.startup(function () {
	Accounts.onCreateUser(function ( options, user ){
		if ( options.profile ) {
			user.profile = options.profile;
			if ( options.profile.numConnections ) {
				user.profile.name = options.profile.firstName + " " + options.profile.lastName
			}
		}
		return user
	})
});
