### ISSUE TITLE
There is an extra notice showing even when not needed

### ISSUE THREAD

**Issue by fafournier** [PoBuchi/meteor-accounts-linkedin#23]
"Note: You're using accounts-ui and accounts-linkedin,
but didn't install the configuration UI for the LinkedIn
OAuth. You can install it with:
    meteor add linkedin-config-ui"

is showing all the time, even if pauli:linkedin-config-ui is added and even if service-configuration is removed after everything is configured

**Comment by EddieFloresLive** [comment]
👍
