### ISSUE TITLE
LinkedIn drops OAuth 1

### ISSUE THREAD

**Issue by killerchip** [PoBuchi/meteor-accounts-linkedin#29]
According to the following, LinkedIn will drop support for OAuth 1.0 on March 1st, 2019.

https://engineering.linkedin.com/blog/2018/12/developer-program-updates

It will only allows OAuth2. 
Does this package currently uses OAuth2. By default? or we need to do something special?

**Comment by PoBuchi** [comment]
OAuth2

**Comment by killerchip** [comment]
Hello,

Sorry to raise this issue again. My investigation shows that the package as it is currently it does not support the changes for V2 API of LinkedIn.

This means on March 1st 2019 the package will not be able to authenticate LinkedIn users.

I'm explaining:
According to this:
https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq

LinkedIn will drop support for the `r_basicprofile` permission. Its replacement will be the `r_liteprofile` permission.

Currently if you use 
```
Meteor.loginWithLinkedin({
            requestPermissions: ['r_basicprofile', 'r_liteprofile', 'r_emailaddress']
 }
```
everything works fine. You are able to login and also access V2 API (provided that your LinkedIn App has access to V2 API).

But if you drop the `r_basicprofile` ( which will be a requirement ), the authentication will not work. It fails with the error:

```
 Error in OAuth Server: Failed to fetch identity from LinkedIn. failed [403] {   "errorCode": 0,   "message": "Access to site-standard-profile-request denied",   "requestId": "******",   "status": 403,   "timestamp": ******** }
I20181228-14:10:57.479(2)? Exception while invoking method 'login' { Error: Failed to fetch identity from LinkedIn. failed [403] {   "errorCode": 0,   "message": "Access to site-standard-profile-request denied",   "requestId": "*********",   "status": 403,   "timestamp": ********** }
I20181228-14:10:57.479(2)?     at getIdentity (packages/pauli:linkedin-oauth/linkedin-server.js:116:11)
I20181228-14:10:57.479(2)?     at Object.handleOauthRequest (packages/pauli:linkedin-oauth/linkedin-server.js:7:18)
I20181228-14:10:57.479(2)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
I20181228-14:10:57.480(2)?     at middleware (packages/oauth/oauth_server.js:161:5)
I20181228-14:10:57.480(2)?     at ********/.meteor/packages/promise/.0.11.2.1esmk5n.w6u9++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20181228-14:10:57.483(2)?   message: 'Failed to fetch identity from LinkedIn. failed [403] {   "errorCode": 0,   "message": "Access to site-standard-profile-request denied",   "requestId": "*******",   "status": 403,   "timestamp": *********** }' }
```

I think this issue needs to re-open.

Kind Regards

**Comment by PoBuchi** [comment]
Thx, will do updates in coming weeks

**Comment by PoBuchi** [comment]
V2 is live
