### ISSUE TITLE
Option to ignore getImage function

### ISSUE THREAD

**Issue by juhojo** [PoBuchi/meteor-accounts-linkedin#31]
Hi,

I noticed that the package, for me at least, fails to function with LinkedIn profiles without a profile picture. Could this issue be addressed as profile picture is an optional field in LinkedIn and it is not unheard of that people do not add a profile pic.

I went through the compiled code and it seems that there is no option to disable `getImage()` function from being called? If I am mistaken, and it is simple, could you provide an example in the README.md.

Thanks in advance.

**Comment by PoBuchi** [comment]
Hi @juhojo,
well it's supposed to ignore it when LInkedin returns undefined profileImage, unless they actually returning smt, need to check

**Comment by PoBuchi** [comment]
@juhojo Please replicate, as I can't seem to be able to do so

**Comment by juhojo** [comment]
Hi, I got this:
```
I20190607-11:40:08.109(3)? Exception while invoking method 'login' TypeError: Cannot read property 'displayImage~' of undefined
I20190607-11:40:08.110(3)?     at getImage (packages/pauli:linkedin-oauth/linkedin-server.js:5:25)
I20190607-11:40:08.111(3)?     at Object.OAuth.registerService.query [as handleOauthRequest] (packages/pauli:linkedin-oauth/linkedin-server.js:146:21)
I20190607-11:40:08.113(3)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
I20190607-11:40:08.114(3)?     at middleware (packages/oauth.js:195:5)
I20190607-11:40:08.114(3)?     at /home/juho/.meteor/packages/promise/.0.10.2.upukqw.6vf1++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```
, but after making alterations to elsewhere in my source code (and by adding a profile pic) it worked fluently. This could mean that there were errors in my code and not the package. The error was likely in my source code.

Thanks for solving the issue so fast :+1:

**Comment by PoBuchi** [comment]
@juhojo 👌🏻
