### ISSUE TITLE
Bad data on login

### ISSUE THREAD

**Issue by tarikmehic** [PoBuchi/meteor-accounts-linkedin#32]
Hello package works great, but for some reason it creates bad data on register/login: `profile.name : "[object Object] [object Object]"`

Is there any possibility to get response in the callback function, so I can maybe call a method to get the correct data?

**Comment by PoBuchi** [comment]
you can use window.LinkedIn.requestCredential, and if you can make demo project for this issue I will take a look sooner

**Comment by PoBuchi** [comment]
@tarikmehic you don't get bad data, if you check readme you will see what kind of data object is returned to your user.profile. 

```
linkedinId, // Specific user id for your application only
    firstName:{
      localized:{
         en_US:'Tina'
      },
      preferredLocale:{
         country:'US',
         language:'en'
      }
    },
    lastName:{
      localized:{
         en_US:'Belcher'
      },
      preferredLocale:{
         country:'US',
         language:'en'
      }
    },
    profilePicture: {
      displayImage, // URN media handle
      identifiersUrl, // Array of links to all available identifiers
    },
    email, // First email from received emails during authentication
    emails, // Array of all received emails during authentication
```
