### ISSUE TITLE
Error in OAuth Server: unauthorized_scope_error

### ISSUE THREAD

**Issue by nicolsondsouza** [PoBuchi/meteor-accounts-linkedin#33]
accounts-linkedin 

Doesn't go well with accounts-ui 

As per latest package I am getting below error.

"Error in OAuth Server: unauthorized_scope_error"

Thanks

**Comment by PoBuchi** [comment]
@nicolsondsouza this is LinkedIn API scope error, not package. Most likely you are requesting data from scope you are not authorized to do so. Read LinkedIn APi docs.

**Comment by nicolsondsouza** [comment]
Yes, I realize that the development app I had on LinkedIn was very old and
need some action to be made to agree some terms, afterwards it was all good.


Thank you for the response.

I will close the issue if it hasn't already.

**Comment by PoBuchi** [comment]
No worries
